/*-------------------------------------------------------------------------
 *
 * pl_unreserved_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef PL_UNRESERVED_KWLIST_D_H
#define PL_UNRESERVED_KWLIST_D_H

#include "parser/kwlookup.h"

static const char UnreservedPLKeywords_kw_string[] =
	"absolute\0"
	"alias\0"
	"alter\0"
	"array\0"
	"as\0"
	"backward\0"
	"bulk\0"
	"call\0"
	"catalog_name\0"
	"class_origin\0"
	"collect\0"
	"column_name\0"
	"commit\0"
	"condition\0"
	"constant\0"
	"constraint_catalog\0"
	"constraint_name\0"
	"constraint_schema\0"
	"continue\0"
	"current\0"
	"cursor\0"
	"cursor_name\0"
	"debug\0"
	"detail\0"
	"distinct\0"
	"do\0"
	"dump\0"
	"errcode\0"
	"error\0"
	"except\0"
	"exceptions\0"
	"false\0"
	"first\0"
	"forward\0"
	"found\0"
	"function\0"
	"handler\0"
	"hint\0"
	"immediate\0"
	"index\0"
	"info\0"
	"instantiation\0"
	"intersect\0"
	"is\0"
	"iterate\0"
	"last\0"
	"leave\0"
	"log\0"
	"merge\0"
	"message\0"
	"message_text\0"
	"multiset\0"
	"mysql_errno\0"
	"next\0"
	"no\0"
	"notice\0"
	"number\0"
	"option\0"
	"package\0"
	"perform\0"
	"pg_exception_context\0"
	"pg_exception_detail\0"
	"pg_exception_hint\0"
	"pragma\0"
	"prior\0"
	"procedure\0"
	"query\0"
	"record\0"
	"relative\0"
	"release\0"
	"repeat\0"
	"replace\0"
	"resignal\0"
	"result_oid\0"
	"returned_sqlstate\0"
	"reverse\0"
	"rollback\0"
	"row_count\0"
	"rowtype\0"
	"save\0"
	"savepoint\0"
	"schema_name\0"
	"scroll\0"
	"signal\0"
	"slice\0"
	"sqlexception\0"
	"sqlstate\0"
	"sqlwarning\0"
	"stacked\0"
	"subclass_origin\0"
	"sys_refcursor\0"
	"table\0"
	"table_name\0"
	"true\0"
	"type\0"
	"union\0"
	"until\0"
	"use_column\0"
	"use_variable\0"
	"variable_conflict\0"
	"varray\0"
	"warning\0"
	"with";

static const uint16 UnreservedPLKeywords_kw_offsets[] = {
	0,
	9,
	15,
	21,
	27,
	30,
	39,
	44,
	49,
	62,
	75,
	83,
	95,
	102,
	112,
	121,
	140,
	156,
	174,
	183,
	191,
	198,
	210,
	216,
	223,
	232,
	235,
	240,
	248,
	254,
	261,
	272,
	278,
	284,
	292,
	298,
	307,
	315,
	320,
	330,
	336,
	341,
	355,
	365,
	368,
	376,
	381,
	387,
	391,
	397,
	405,
	418,
	427,
	439,
	444,
	447,
	454,
	461,
	468,
	476,
	484,
	505,
	525,
	543,
	550,
	556,
	566,
	572,
	579,
	588,
	596,
	603,
	611,
	620,
	631,
	649,
	657,
	666,
	676,
	684,
	689,
	699,
	711,
	718,
	725,
	731,
	744,
	753,
	764,
	772,
	788,
	802,
	808,
	819,
	824,
	829,
	835,
	841,
	852,
	865,
	883,
	890,
	898,
};

#define UNRESERVEDPLKEYWORDS_NUM_KEYWORDS 103

static int
UnreservedPLKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[207] = {
		0,     70,    23,    68,    0,     14,    13,    65,
		32767, 0,     19,    -5,    0,     85,    0,     18,
		9,     32767, 34,    18,    32767, 74,    8,     0,
		32767, 0,     32767, 0,     6,     72,    -9,    32767,
		32767, 32767, 32767, 32767, 42,    -85,   32767, 75,
		32767, 74,    99,    32767, 32767, 91,    32767, -49,
		32767, 32767, 32767, 32767, 32767, 10,    9,     0,
		-76,   32767, 0,     32767, 32767, 81,    5,     32767,
		32767, 32767, 32767, 90,    62,    9,     32767, 33,
		66,    32767, 32767, 6,     -26,   32767, 97,    15,
		102,   6,     0,     22,    32767, 32767, 3,     32767,
		4,     28,    0,     0,     87,    -3,    0,     11,
		33,    32767, -21,   32767, 25,    28,    0,     -17,
		32767, 57,    0,     36,    -16,   0,     -20,   35,
		32,    32767, 32767, 122,   32767, 32767, 46,    32767,
		32767, 32767, 61,    70,    0,     32767, -14,   32767,
		32767, 0,     55,    32767, -47,   32767, 0,     16,
		47,    32767, 0,     0,     -64,   32767, 32767, -76,
		0,     19,    32767, 36,    7,     32767, 68,    81,
		94,    32767, 98,    101,   32767, 32767, 0,     32767,
		32767, -60,   44,    0,     89,    -5,    -34,   2,
		0,     32767, 58,    32767, 32767, 32767, 32767, 32767,
		32767, 32767, 2,     -19,   93,    32767, 32767, 32767,
		37,    49,    27,    55,    3,     15,    128,   12,
		-43,   60,    32767, 0,     32767, 0,     32767, 0,
		62,    32767, 32767, 104,   20,    32767, 1
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 17 + c;
	}
	return h[a % 207] + h[b % 207];
}

static const ScanKeywordList UnreservedPLKeywords = {
	UnreservedPLKeywords_kw_string,
	UnreservedPLKeywords_kw_offsets,
	UnreservedPLKeywords_hash_func,
	UNRESERVEDPLKEYWORDS_NUM_KEYWORDS,
	20
};

#endif							/* PL_UNRESERVED_KWLIST_D_H */
